from collections import Counter
import json

import networkx as nx
import pandas as pd
import colorcet


# Colors used for different graph Modularity Classes
COLORS = colorcet.glasbey_dark
OUTPUT_JSON = "../viz/public/descriptions.json"

NODE_SCALING = 1.25
# GraphML file generated by Gephi
INPUT_GRAPHML = "graphml/descriptions_layout.graphml"

CLUSTERS = [
    {"key": "0", "clusterLabel": "No-code"},
    {"key": "1", "clusterLabel": "Python & scraping"},
    {"key": "2", "clusterLabel": "Social media"},
    {"key": "3", "clusterLabel": "Databases & applications"},
    {"key": "4", "clusterLabel": "R & data cleaning"},
    {"key": "5", "clusterLabel": "Git"},
    {"key": "6", "clusterLabel": "Documents & AI"},
    {"key": "7", "clusterLabel": "Web dev"},
    {"key": "8", "clusterLabel": "Maps & census"},
    {"key": "9", "clusterLabel": "Excel"}
]

BOUND = 800
BOUNDING_BOX = {"x": [-BOUND, BOUND], "y": [-BOUND,BOUND]}

LABEL_THRESHOLD = 12

if __name__ == "__main__":

    G = nx.read_graphml(path=INPUT_GRAPHML)

    _nodes_df = pd.DataFrame.from_dict(
        dict(G.nodes(data=True)), orient="index"
    ).reset_index(drop=True)
    _edges_df = nx.to_pandas_edgelist(G=G)

    nodes_df = _nodes_df[["x", "y", "label", "size", "Modularity Class"]]
    edges_df = _edges_df[["source", "target"]]

    nodes_df["cluster"] = nodes_df["Modularity Class"]
    nodes_df["cluster"].fillna("Other", inplace=True)
    nodes_df.drop("Modularity Class", axis="columns", inplace=True)

    label_to_index = {t[0] : i for i, t in enumerate(Counter(list(edges_df['source']) + list(edges_df['target'])).most_common())}

    nodes_df["key"] = nodes_df['label'].map(label_to_index)
    nodes_df["size"] /= NODE_SCALING
    nodes = nodes_df.to_dict(orient="records")

    edges = [[label_to_index[e["source"]], label_to_index[e["target"]]] for e in edges_df.to_dict(orient="records")]

    data = {
        "nodes": nodes,
        "edges": edges,
        "clusters": [
            {**cluster, "color": COLORS[i]} for i, cluster in enumerate(CLUSTERS)
        ],
        "bbox": BOUNDING_BOX,
        'labelThreshold': LABEL_THRESHOLD
    }

    with open(OUTPUT_JSON, "w") as f:
        json.dump(obj=data, fp=f, separators=(",", ":"))